export const Languages = [
    { name: "Afrikaans" },
    { name: "azərbaycan" },
    { name: "bosanski" },
    { name: "català" },
    { name: "Čeština" },
    { name: "Cymraeg" },
    { name: "Dansk" },
    { name: "Deutsch" },
    { name: "eesti" },
    { name: "English (United Kingdom)" },
    { name: "English (United States)" },
    { name: "Español (España)" },
    { name: "Español (Latinoamérica)" },
    { name: "euskara" },
    { name: "Filipino" },
    { name: "Français (Canada)" },
    { name: "Français (France)" },
    { name: "Gaeilge" },
    { name: "galego" },
    { name: "Hrvatski" },
    { name: "Indonesia" },
    { name: "isiZulu" },
    { name: "íslenska" },
    { name: "Italiano" },
    { name: "Kiswahili" },
    { name: "latviešu" },
    { name: "lietuvių" },
    { name: "magyar" },
    { name: "Melayu" },
    { name: "Nederlands" },
    { name: "norsk" },
    { name: "o‘zbek" },
    { name: "polski" },
    { name: "Português (Brasil)" },
    { name: "Português (Portugal)" },
    { name: "română" },
    { name: "shqip" },
    { name: "Slovenčina" },
    { name: "slovenščina" },
    { name: "srpski (latinica)" },
    { name: "Suomi" },
    { name: "Svenska" },
    { name: "Tiếng Việt" },
    { name: "Türkçe" },
    { name: "Ελληνικά" },
    { name: "беларуская" },
    { name: "български" },
    { name: "кыргызча" },
    { name: "қазақ тілі" },
    { name: "македонски" },
    { name: "монгол" },
    { name: "Русский" },
    { name: "српски (ћирилица)" },
    { name: "Українська" },
    { name: "ქართული" },
    { name: "հայերեն" },
    { name: "עברית" },
    { name: "اردو" },
    { name: "العربية" },
    { name: "فارسی" },
    { name: "አማርኛ" },
    { name: "नेपाली" },
    { name: "मराठी" },
    { name: "हिन्दी" },
    { name: "অসমীয়া" },
    { name: "বাংলা" },
    { name: "ਪੰਜਾਬੀ" },
    { name: "ગુજરાતી" },
    { name: "ଓଡ଼ିଆ" },
    { name: "தமிழ்" },
    { name: "తెలుగు" },
    { name: "ಕನ್ನಡ" },
    { name: "മലയാളം" },
    { name: "සිංහල" },
    { name: "ไทย" },
    { name: "ລາວ" },
    { name: "မြန်မာ" },
    { name: "ខ្មែរ" },
    { name: "한국어" },
    { name: "中文（香港）" },
    { name: "日本語" },
    { name: "简体中文" },
];
